name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - '!README.md'
      - '!docker-compose.yml'
  pull_request:
    paths:
      - '!README.md'
      - '!docker-compose.yml'
    types:
    - opened
    - closed
    branches: [ main ]

jobs:

  build:
    name: "Build Linux"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . -t dechertnicholas/space-engineers-ds-linux:latest
    
    - name: Docker Login
      if: github.event.pull_request.merged == true
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Publish the Docker image
      if: github.event.pull_request.merged == true
      run: docker push dechertnicholas/space-engineers-ds-linux:latest
